### ISSUE TITLE
Add Pinecone VectorDB class

### ISSUE THREAD

**Issue by zmccormick7** [D-Star-AI/dsRAG#1]
The VectorDB component is a critical part of the system, and we want to support all of the major players. You can add support for a new one by subclassing the VectorDB base class and making sure you have all of the required methods.

**Comment by rohanprashant12** [comment]
+1 on this request

**Comment by zmccormick7** [comment]
I went ahead and started working on this: PR #57

**Comment by zmccormick7** [comment]
Closed by #57
