### ISSUE TITLE
feat: execute queries `get_all_ranked_results` concurrently

### ISSUE THREAD

**Issue by obviyus** [D-Star-AI/dsRAG#43]
Hi, I've been testing `dsRAG` and it's working really well. However, right now `get_all_ranked_results` performs vector search sequentially for all queries. If we use something like `auto_query` and end up with > 10 search queries the search takes quite a while.

I've made a small change to use `ThreadPoolExecutor` like so:
```python
    def get_all_ranked_results(self, search_queries: list[str]):
        """
        - search_queries: list of search queries
        """
        with concurrent.futures.ThreadPoolExecutor() as executor:
            future_to_query = {executor.submit(self.search, query, 200): query for query in search_queries}
            all_ranked_results = []
            for future in concurrent.futures.as_completed(future_to_query):
                ranked_results = future.result()
                all_ranked_results.append(ranked_results)
        
        return all_ranked_results
```

...which cuts down the query time massively in case of many `search_queries`.

I'd be happy to make a PR for this if you find it useful!

**Comment by zmccormick7** [comment]
Yep, this should definitely be done in parallel by default. If you could make a PR for this, that would be great!

Only thing to double check is that the results are still ordered in the same way as the search queries using this method, as the order of the all_ranked_results list does matter.
