### ISSUE TITLE
Does it only support text?

### ISSUE THREAD

**Issue by Sere1nz** [D-Star-AI/dsRAG#58]
What about table and image in pdf?

**Comment by zmccormick7** [comment]
We'll be adding support for this very soon.

**Comment by Sere1nz** [comment]
Thank you! 
might also consider extract text /image from scanned pdf format by using OCR

**Comment by zmccormick7** [comment]
The method we're working on uses a VLM to extract both text and image bounding boxes, so it should work just as well for scanned PDFs.
