### ISSUE TITLE
kb.query() empty result when kb instanciated with ChromaDB as a vector_db

### ISSUE THREAD

**Issue by AnthoSocofer** [D-Star-AI/dsRAG#66]
Hi,
I am testing dsRag with chroma but I have troubles using the query() method. It returns empty list. When using the search method it works fine.

here is how I instanciate the knowledge_base instance : 

def create_chroma_kb(kb_id: str, title: str, description: str, language: str, storage_directory: str):
    """Create a knowledge base using ChromaDB with proper permissions."""
    # Expand user directory if using ~
    storage_directory = os.path.expanduser(storage_directory)
    
    # Create all necessary directories with full permissions
    os.makedirs(storage_directory, mode=0o777, exist_ok=True)
    os.makedirs(os.path.join(storage_directory, "vector_storage"), mode=0o777, exist_ok=True)
    os.makedirs(os.path.join(storage_directory, "metadata"), mode=0o777, exist_ok=True)
    
    # Delete existing ChromaDB instance if it exists
    vector_db = ChromaDB(kb_id=kb_id, storage_directory=storage_directory)
    try:
        vector_db.delete()
    except Exception:
        pass
        
    # Create new ChromaDB instance
    vector_db = ChromaDB(kb_id=kb_id, storage_directory=storage_directory)
    
    # Create KnowledgeBase instance
    kb = KnowledgeBase(
        kb_id=kb_id,
        title=title,
        description=description,
        language=language,
        storage_directory=storage_directory,
        embedding_model=OpenAIEmbedding(),
        reranker=CohereReranker(model="rerank-multilingual-v3.0"),
        vector_db=vector_db,
        exists_ok=True
    )
    
    return kb
    
    Any clue on how to make it works ?

**Comment by AnthoSocofer** [comment]
After going into the code the pain point is in: best_segments, scores which are empty.
best_segments, scores = get_best_segments(
    all_relevance_values=all_relevance_values,
    document_splits=document_splits,
    max_length=max_length,
    overall_max_length=overall_max_length,
    minimum_value=minimum_value,
)

**Comment by zmccormick7** [comment]
If the search method is returning results, then it isn't an issue with the vector DB. It just means there aren't any segments with relevance above the minimum_value threshold. You can try setting that cutoff to a lower value (in rse_params).

**Comment by AnthoSocofer** [comment]
thanks for the advice :) Indeed, it was depending on it to return a result
